name: "AntiGuest"
version: $version
main: "de.cubeisland.antiguest.AntiGuest"
dev-url: "http://dev.bukkit.org/server-mods/antiguest"
authors:
  - "Quick_Wango"
  - "SweetieBelle"
api-version: 1.16
description: "Prevents guests from griefing."
website: "http://cubeisland.de"
commands:
  antiguest:
    usage: "/<command> <subcommand> [arguments...]"
    description: "This is the base command for all AntiGuest commands"
    aliases:
      - "ag"
permissions:
  antiguest.violation-notification:
    description: "Allows the player to get the violation notice"
    default: false
  antiguest.*:
    description: "Allows the player to do everything"
    default: op
    children:
      antiguest.preventions.*: true
      antiguest.commands.*: true
